export const searchList = [
  {
    mainTitle: "Flower Request",
    alternativeTitles: ["bouquet", "gift", "checkout", "send"],
    url: "/service-requests",
  },
  {
    mainTitle: "About Us",
    alternativeTitles: [
      "information",
      "students",
      "development",
      "developers",
      "",
    ],
    url: "/about-us",
  },
  {
    mainTitle: "CSV Table",
    alternativeTitles: ["nodes", "edges", "import", "export"],
    url: "/csv-table",
  },
  {
    mainTitle: "Request Logs",
    alternativeTitles: [
      "information",
      "backend",
      "database",
      "logs",
      "request",
    ],
    url: "/request-log-Page",
  },
  {
    mainTitle: "Insight",
    alternativeTitles: ["insight", "graphs", "information", "service requests"],
    url: "/insight",
  },
  {
    mainTitle: "Map Editor",
    alternativeTitles: ["nodes", "edges", "map", "edit"],
    url: "/map-editor/map",
  },
  {
    mainTitle: "Map Editor Table",
    alternativeTitles: [
      "table",
      "edit",
      "map",
      "nodes",
      "edges",
      "coordinates",
      "coords",
    ],
    url: "/map-editor/table",
  },
  {
    mainTitle: "Navigation",
    alternativeTitles: [
      "search",
      "home",
      "map",
      "path finding",
      "pathfinding",
      "location",
    ],
    url: "/home",
  },
  {
    mainTitle: "Main Page",
    alternativeTitles: ["home", "main", "hero", "log in", "login"],
    url: "/",
  },
  {
    mainTitle: "Sanitation Request",
    alternativeTitles: ["Cleaning", "maintenance", "dirty", "mop"],
    url: "/service-requests",
  },
  {
    mainTitle: "Patient Transport",
    alternativeTitles: ["drive", "car", "ambulance", "helicopter"],
    url: "/service-requests",
  },
  {
    mainTitle: "Security Request",
    alternativeTitles: [
      "police",
      "cops",
      "danger",
      "violence",
      "safety",
      "badge",
      "secure",
      "perimeter",
    ],
    url: "/service-requests",
  },
  {
    mainTitle: "Medication Request",
    alternativeTitles: [
      "drug",
      "pharmacy",
      "pill",
      "dose",
      "high",
      "medication",
      "prescription",
      "meds",
      "remedy",
      "pharmaceutical",
      "antibiotic",
      "antidepressant",
      "painkiller",
      "analgesic",
      "antacid",
      "antihistamine",
      "antibacterial",
      "antiviral",
      "steroid",
      "diuretic",
      "anti-inflammatory",
      "anesthetic",
      "sedative",
      "tranquilizer",
      "psychotropic",
      "hypnotic",
      "corticosteroid",
      "antifungal",
      "antiseptic",
      "anticoagulant",
      "antiepileptic",
      "antispasmodic",
      "antipyretic",
      "antitussive",
      "expectorant",
      "antimalarial",
      "immunosuppressant",
      "bronchodilator",
      "vasodilator",
      "vasoconstrictor",
      "antidiarrheal",
      "laxative",
      "antiemetic",
      "antiarrhythmic",
      "antihypertensive",
      "anticholinergic",
      "antihyperlipidemic",
      "antihyperglycemic",
      "antiparasitic",
      "antitumor",
      "antimicrobial",
      "anticoagulant",
      "antiviral",
      "antiseptic",
      "analgesic",
      "anti-inflammatory",
      "antipyretic",
      "anticonvulsant",
      "anxiolytic",
      "antidepressant",
      "antipsychotic",
      "antimanic",
      "mood stabilizer",
      "stimulant",
      "sedative",
      "hypnotic",
      "tranquilizer",
      "muscle relaxant",
      "antispasmodic",
      "dopamine agonist",
      "serotonin antagonist",
      "acetylcholine antagonist",
      "norepinephrine reuptake inhibitor",
      "selective serotonin reuptake inhibitor",
      "benzodiazepine",
      "proton pump inhibitor",
      "histamine H2 receptor antagonist",
      "glucocorticoid",
      "beta blocker",
      "calcium channel blocker",
      "ACE inhibitor",
      "angiotensin II receptor antagonist",
      "antithyroid agent",
      "thyroid hormone",
      "insulin",
      "oral hypoglycemic",
      "blood thinner",
      "blood pressure",
      "heart",
      "cholesterol",
      "immunization",
      "vaccination",
      "injection",
      "tablet",
      "capsule",
      "liquid medicine",
      "dosage",
      "prescription refill",
      "drugstore",
      "dispensary",
      "pharmacist",
      "OTC",
      "pharmacology",
      "clinical pharmacy",
      "prescription",
      "refill",
    ],
    url: "/service-requests",
  },
];
